def get_index():
    page = ('<!DOCTYPE html>\n'
            '<html lang="en">\n'
            '<head>\n'
            '	<title>If These Trees Could Talk</title>\n'
            '	<meta charset="utf-8"/>\n'
            '\n'
            '	<link rel="stylesheet" type="text/css" href="css/style.css"/>\n'
            '	\n'
            '	<meta name="description" content="This is a fan website for the post-rock group: &quot; IF THESE TREES COULD TALK&quot;">\n'
            '	<meta name="keywords" content="IF THESE TREES COULD TALK, Red Forest, Above the Earth Below the Sky, The Bones of a Dying World, Post Rock">\n'
            '	<meta name="author" content="Fatih Altınpınar">\n'
            '	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />\n'
            '</head>\n'
            '<body>\n'
            '	<div class="container">\n'
            '		<!-- navigation -->\n'
            '		<header>\n'
            '			<div class="navBar">\n'
            '				<a href="index.html" class="navImg">\n'
            '						<img src="img/logo.svg" alt="Tree Logo">\n'
            '				</a>\n'
            '				<div class="navLinks">\n'
            '					<a class="active" href="index.html">HOME</a>\n'
            '					<a href="about.html">ABOUT</a>\n'
            '					<a href="members.html">MEMBERS</a>\n'
            '					<a href="songs.html">SONGS</a>\n'
            '					\n'
            '				</div>\n'
            '			</div>\n'
            '		</header>\n'
            '		<div class="content">\n'
            '			<h1>IF THESE TREES COULD TALK</h1>\n'
            '			<h2>What do they have to say?</h2>\n'
            '			<p>Personally I don\'t like changes. I like doing the same thing over and over again. Just because I like it. Maybe <span style="color:red; font-weight:bold;">change</span> is a really important thing for you but not for me, especially in songs that I listen to. I like listening the same thing over and over again. Maybe the reason behind this is that I like instrumental music. I feel different every time I listen to, like it is a deeper level, another chapter, another page...</p>\n'
            '\n'
            '			<p>I met this group back in March 2015 with the song &quot;Barren Lands Of the Modern Dinosaur&quot;. I added it to <a href="https://open.spotify.com/user/fatihaltinpinar/playlist/1OwU6Kd1IypR8WcjSxe50k?si=i1naHw9nSFi9ZutMe48kPw">my Spotify playlist</a> then left it there for a while. I was listening to random things back then. Let&#39;s say I did not have a music taste. :)</p>\n'
            '\n'
            '			\n'
            '			<img class="pageEndLogo" src="img/bottomTrees.svg" alt="If These Trees Could Talk">\n'
            '\n'
            '\n'
            '		</div>	\n'
            '		<div class="footer">\n'
            '			<a class="sources" href="sources.html">Sources</a>\n'
            '			<span class="footerText">All music rights are owned by <a href="https://twitter.com/treescouldtalk">If These Trees Could Talk</a></span>\n'
            '		</div>\n'
            '	</div>\n'
            '</body>\n'
            '</html>\n'
            '    ')
    return page